### PR TITLE
Displayed values for all properties in admin

### PR DESCRIPTION
**Pull request by Daniel-KM**
In the admin resource show pages, it's simpler for users to display the values for all properties.

### CODE REVIEW

**Comment by zerocrates** [comment]
I can definitely see this being useful.

I think I'd prefer it to be controlled by a "show all properties on admin" setting, though.

**Comment by Daniel-KM** [comment]
I prepared a branch for that, but I pulled on master.

**Comment by zerocrates** [comment]
I'm fine with the default being enabled like you have it here, that makes sense.

Though, at a glance I think this is missing the little piece for updating the config form with the current value of the toggle. Otherwise I think it looks good.

**Comment by Daniel-KM** [comment]
I did it automatically in other modules, so I forgot it here.

**Comment by zerocrates** [comment]
Thanks, Daniel.

Looks great.

**Pull request merged**
